# Generated by Django 4.2.7 on 2025-12-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentlocontribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentscore',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AB', 'AB'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], help_text='Letter grade for this assessment (automatically calculated)', max_length=2, null=True),
        ),
    ]
