# Generated by Django 4.2.7 on 2025-12-29 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLOPOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_percentage', models.DecimalField(decimal_places=2, help_text='Percentage contribution of this LO to the PO (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('department_program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_contributions', to='courses.departmentprogramoutcome')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_po_contributions', to='courses.learningoutcome')),
            ],
            options={
                'ordering': ['department_program_outcome', 'learning_outcome'],
                'unique_together': {('learning_outcome', 'department_program_outcome')},
            },
        ),
    ]
