# Generated by Django 4.2.7 on 2025-12-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_departmentprogramoutcome_departmentlopocontribution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentLOPOContribution',
        ),
        migrations.DeleteModel(
            name='DepartmentProgramOutcome',
        ),
    ]
